---
thread:
  workers: 2
  worker-limit: 256
  collection-period: 1

mysql:
  username: "doge"
  database: "schema"
  host: 127.0.0.1
  password: "123"
  port: 3306

scoreboard:
  main: "&l&eWITHERGAMES"
  duel: "&l&eDUELS"

gameChat: "{PLAYER}: {msg}"
...
