---
thread:
  workers: 2
  worker-limit: 256
  collection-period: 1

mysql:
  username: "u10837_ZPhjmLGbFQ"
  database: "s10837_dave-testing-field"
  host: "45.134.8.163"
  password: "DF2tm1v.V9@g1=k46.eSAjaG"
  port: 3306

scoreboard:
  main: "&l&eWITHERGAMES"
  duel: "&l&eDUELS"
...
